{{- if .Values.helmChart.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "go-aviasales-task.fullname" . }}
  labels:
    service: {{ .Release.Name }}
    app: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  {{- if .Values.helmChart.ingress.useLocalHttps }}
  tls:
  - hosts:
    - {{ .Values.helmChart.ingress.url }}
    secretName: {{ .Values.helmChart.ingress.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.helmChart.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "go-aviasales-task.fullname" . }}
          servicePort: http
{{- end }}
