{{- if .Values.helmChart.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-redis-secret
  labels:
    app: {{ .Chart.Name }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-400"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  redis-password: {{ randAlphaNum 32 | b64enc }}
{{- end }}
