apiVersion: v1
kind: Service
metadata:
  name: {{ template "go-aviasales-task.fullname" . }}
  labels:
    service: {{ .Release.Name }}
    app: {{ .Chart.Name }}
spec:
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}

